### ISSUE TITLE
GSV signalID should be hexadecimal, not integer

### ISSUE THREAD

**Issue by flytrex-vadim** [semuconsulting/pynmeagps#11]
example message from u-blox F9P receiver:

$GBGSV,2,2,06,14,55,175,46,40,29,043,18,B*06

Not the 0xB value at last position

**Comment by semudev2** [comment]
Hi @flytrex-vadim,

You're right, the SignalID field is officially defined as hexadecimal in the documentation, e.g. ...

<img width="686" alt="Screenshot 2022-01-14 at 07 37 47" src="https://user-images.githubusercontent.com/94571928/149470091-6beabd3e-7be2-4da5-bb98-bb2f6cdfaa0a.png">

... but when one refers to the associated Table of Signal Identifiers they all appear to be integers so this seemed to be the most appropropriate and useful format to parse to:

<img width="419" alt="Screenshot 2022-01-14 at 07 38 19" src="https://user-images.githubusercontent.com/94571928/149470285-0d58e7ba-3d59-4df2-8087-dd9884dc58ee.png">

But if this causes a problem in practice, by all means advise and we can happily revert to the documented hex format. What do you think?

**Comment by flytrex-vadim** [comment]
Hi @semudev2 ,

If you look at the table you've quoted, In protocol version 4.11 the Signal ID for BeiDou B2I signal is indeed 0xB I have encountered from F9P receiver (see above). So the correct action would be to parse them according to the documentation :)

BTW, somewhat off-topic - is there an example of how to parse a stream including a mixture of UBX and NMEA messages while gracefully recovering from exception such as parsing error here ? Parsing errors seem to cause exception from the next() iterator and this stops the loop.

**Comment by semudev2** [comment]
Fair cop! I'll remember to wear my specs the next time I review the docs :) Sorted, will be in next release.

In answer to your secondary question, the graphical client PyGPSClient contains an example of a mixed protocol parsing routine. See the `_parse_data()` method in `serial_handler.py`. Take a look and let me know if it helps at all.

https://github.com/semuconsulting/PyGPSClient/blob/master/pygpsclient/serial_handler.py

Out of interest though, what kind of errors are you getting from the `read()` method in `nmeareader.py` ? Other than problems with the `Stream` object itself, it should normally only throw an error if it encounters a non-NMEA payload and the `nmea-only` flag is set to true. If you think it's failing on errors it should be tolerating, by all means raise a feature request.

**Comment by semudev2** [comment]
actually reopening this - might need a bit more testing
