### ISSUE TITLE
"Universal" reader

### ISSUE THREAD

**Issue by flytrex-vadim** [semuconsulting/pynmeagps#13]
Since u-blox receivers are frequently configured to emit both UBX and NMEA message types, it could be useful to have a reader module that can process such a stream and parse it correctly using both pyubx2 and pynmeagps.

Something like the code in [pygpsclient/serial_handler.py](https://github.com/semuconsulting/PyGPSClient/blob/a2cb54d97af3aa538a4c25a31da1910a24848c40/pygpsclient/serial_handler.py#L316), but packaged for reusability, with an interface like NMEAReader / UBXReader.

**Comment by semudev2** [comment]
ok we can port PYGPSClient's `serial_handler.py` mixed-protocol read routine into a stand-alone CLI example if that helps.

**Comment by flytrex-vadim** [comment]
I think that would be a good step, especially if separated from dependency on Serial and made work with a stream like NMEAReader and UBXReader.

**Comment by semuadmin** [comment]
FYI Provisional implementation as cli utility `gnssdump.py` as part of `pyubx2` rather than `pynmeagps`. Work in progress is in `pyubx2` branch `add-gnssdump-cli-utility`.

**Comment by semuadmin** [comment]
This has hopefully been addressed via https://github.com/semuconsulting/pyubx2/pull/50
