### ISSUE TITLE
Increase Precision of NMEA LAT LON Coordinates from 5 to 7 Decimal Places

### ISSUE THREAD

**Issue by jdadams-usgs** [semuconsulting/pynmeagps#17]
Thank you very much for pynmeagps. It is a wonderful starting point for my project.

I know this may be a ridiculous request but I would appreciate the decimal places on NMEA sentence LAT LON coordinates be increased from 5 to 7 decimal places. I would be happy with 6 but 7 would completely rule out any accuracy concerns.

Please correct me if I am wrong but I believe 5 decimal places provides precision in the 1 - 2 cm range? This is described in this u-blox thread:

https://portal.u-blox.com/s/question/0D52p00008HKCpZCAX/how-to-increase-the-precision-of-latitude-longitude-information-to-6-digits-in-nmea-message

My project is to generate a GPS file in NMEA sentence format compatible with Sensors & Software's EKKO-Project tool for processing Ground Penetrating Radar (GPR) data. My input file will be a POS trajectory file that has been corrected with PPK post processing using Emlid's Emlid Studio. The original GPS data is collected with an Emlid Reach RS2 on a GPR sled. Here are example lines from the resulting POS trajectory file. This input file provides 9 decimal places of precision on decimal degrees. I know these example lines are not "fixed". This data has not been PPKed yet.

% program   : ES 1 Beta 10
% inp file  : C:\Users\acreight\DOI\ALC- Projects - Documents\GPS\New folder\CWSC-1-rove_raw_202204251822_RINEX_3_03\CWSC-1-rove_raw_202204251822.22O
% inp file  : C:\Users\acreight\DOI\ALC- Projects - Documents\GPS\New folder\CWSC-1-rove_raw_202204251822_RINEX_3_03\CWSC-1-rove_raw_202204251822.22P
% obs start : 2022/04/25 18:22:52.0 GPST (week2207 152572.0s)
% obs end   : 2022/04/25 19:48:42.0 GPST (week2207 157722.0s)
%
% (lat/lon/height=WGS84/ellipsoidal,Q=1:fix,2:float,3:sbas,4:dgps,5:single,6:ppp,ns=# of satellites)
%  GPST                  latitude(deg) longitude(deg)  height(m)   Q  ns   sdn(m)   sde(m)   sdu(m)  sdne(m)  sdeu(m)  sdun(m) age(s)  ratio
2022/04/25 18:22:52.000   37.907054390 -107.726219853  3695.9964   5  16   3.2086   3.4894   7.2942  -1.1259   1.7928  -1.3556   0.00    0.0
2022/04/25 18:22:53.000   37.907054256 -107.726219850  3696.0308   5  16   3.2087   3.4896   7.2942  -1.1258   1.7939  -1.3558   0.00    0.0
2022/04/25 18:22:54.000   37.907054019 -107.726218720  3696.0449   5  17   3.1779   3.1165   7.2608  -0.7546   1.4581  -1.2364   0.00    0.0
2022/04/25 18:22:55.000   37.907054206 -107.726219340  3696.0215   5  18   3.1461   3.0529   7.1496  -0.5359   1.1556  -0.9800   0.00    0.0
2022/04/25 18:22:56.000   37.907054341 -107.726219948  3695.9748   5  18   3.1461   3.0530   7.1497  -0.5357   1.1572  -0.9802   0.00    0.0
2022/04/25 18:22:57.000   37.907054426 -107.726220263  3695.9737   5  18   3.1462   3.0532   7.1497  -0.5355   1.1589  -0.9804   0.00    0.0
2022/04/25 18:22:58.000   37.907055122 -107.726221381  3695.7856   5  20   2.9597   2.8730   6.1703   0.8442  -0.6558  -0.8601   0.00    0.0

I know asking for precision greater than 1-2cm is a bit ridiculous. Where possible, I am striving to rule out sources of error as my colleagues research measuring snow depth and density.

Thank you for considering this change.

The non-serialized output of NMEAMessage appears to maintain the original precision. The serialize() output truncates to 5 decimal places:

```
from pynmeagps import NMEAMessage, GET
msg = NMEAMessage('GN', 'GGA', GET, lat=37.907054390, NS='N', lon=107.726219853, EW='W', status='A', posMode='A')
print(msg)
print(msg.serialize().decode("utf-8"))

<NMEA(GNGGA, time=20:58:02.969459, lat=37.90705439, NS=N, lon=-107.726219853, EW=W, quality=0, numSV=0, HDOP=0.0, alt=0.0, altUnit=, sep=0.0, sepUnit=, diffAge=0.0, diffStation=0)>
$GNGGA,205802.96,3754.42326,N,10743.57319,W,0,0,0.0,0.0,,0.0,,0.0,0*71
```

I made an attempt increasing the decimal places in nmeahelpers.py ddd2dmm but it looks like additional changes are need in other functions. The resulting output from serialize

https://github.com/semuconsulting/pynmeagps/blob/master/pynmeagps/nmeahelpers.py#L137

**Comment by semuadmin** [comment]
Hi @jdadams-usgs

I think there may be some confusion here regarding lat/lon formats and decimal precision. The native NMEA lat/lon format is degrees and decimal **minutes** ((d)ddmm.mmmmm) to 5dp - this is an NMEA protocol limitation - but pynmeagps converts this to decimal degrees ((d)dd.ddddddd) retaining the full precision of the original NMEA message. So, for example, 37.9070543 (decimal degrees) is equivalent to 3754.42326 (NMEA degrees and decimal minutes) to a precision of 7dp, equivalent to around 1 cm at the equator. Obviously, pynmeagps cannot enhance the precision of the original NMEA data.

Other GNSS protocols, such as u-blox's UBX protocol, are capable of providing higher precision data (up to 9dp in degrees for High Precision (HPG) devices such as the ZED-F9P)  - equivalent to better than 1 mm - but achieving such accuracy in practice would require highly specialised RTK enhancement techniques.

https://en.wikipedia.org/wiki/Decimal_degrees#Precision

**Comment by jdadams-usgs** [comment]
Thank you very much for the quick reply @semuadmin . Let's consider this closed.

Good to know the NMEA protocol is limited to 5 decimal places although I feel this is arbitrary.

I continue to find reference to others discussing similar NMEA string limitations:

https://learn.sparkfun.com/tutorials/gps-rtk2-hookup-guide/can-i-really-use-nmea-with-a-high-precision-gps-receiver

Thank you for your time.

**Comment by semuadmin** [comment]
Hi @jdadams-usgs 

The Sparkfun link you mention above refers _specifically_ to u-blox devices. u-blox do provide a facility in u-center to increase the NMEA precision to 7 dp in _minutes_ (equivalent to 9dp in _degrees_) for receivers that support this level of precision, but this is in effect a proprietary 'hack' and not part of the NMEA standard. If you configure a compatible u-blox HPG device in this fashion, then pynmeagps will duly reflect this level of precision in its output - it doesn't round the NMEA data to 5dp.

Again, if you need more than 7dp of precision in degrees, then as the link says you may be better off using the UBX protocol with a [suitable HPG device](https://www.u-blox.com/en/positioning-chips-and-modules) - such devices are able to output high precision lat/lon data via UBX messages such as UBX-NAV-HPPOSLLH or UBX-NAV-HPPOSECEF.

**Comment by jdadams-usgs** [comment]
Thank you again for the continued replies. Excellent information and I really appreciate your depth of knowledge.
