### ISSUE TITLE
few notes

### ISSUE THREAD

**Issue by cminton-hub** [semuconsulting/pynmeagps#2]
**Describe the bug**

- In the file example/nmeafile.py line 72-76 is a copy error from your other project pyubx2: self._ubxreader should be self_nmeareader

- In the msgID GBS is one attribute wrong: effLon should be errLon

- For the msgID GSA no distinction is made between the NMEA Talker IDs. This was tested with GPS and GLONASS data. The talker ID GN is always used.

Please specify the pynmeagps version:
1.0.0

**To Reproduce**

USE any type of nmea data

**Desktop (please complete the following information):**

Windows 10, VSC

**GNSS/GPS Device (please complete the following information as best you can):**

 - Device Model/Generation: NEO-M8U-0
 - Firmware Version: UDR 1.00
 - Protocol: 19.00

Feel free to ask any questions.

Thanks for the awesome projects.

cy
cminton

**Comment by semuadmin** [comment]
Thanks for these - appreciated. 

First two obviously fat finger trouble, but I'm not sure if the third one is actually a pynmeagps issue or a feature of the receiver itself? Can you clarify what you expect to get vs. what you're actually getting?

I presume what you mean is that GSA messages for different GNSS all come in with the same talker ID (GN) but with different systemIds, whereas other message types like GSV come in with different talker IDs (GA, GB, GL, GP, etc.) e.g.

<NMEA(**GN**GSA, opMode=A, navMode=3, svid_01=27, svid_02=29, svid_03=26, svid_04=18, svid_05=, svid_06=, svid_07=, svid_08=, svid_09=, svid_10=, svid_11=, svid_12=, PDOP=2.09, HDOP=1.67, VDOP=1.25, **systemId=1**)>
<NMEA(**GN**GSA, opMode=A, navMode=3, svid_01=79, svid_02=81, svid_03=87, svid_04=82, svid_05=, svid_06=, svid_07=, svid_08=, svid_09=, svid_10=, svid_11=, svid_12=, PDOP=2.09, HDOP=1.67, VDOP=1.25, **systemId=2**)>
<NMEA(**GN**GSA, opMode=A, navMode=3, svid_01=, svid_02=, svid_03=, svid_04=, svid_05=, svid_06=, svid_07=, svid_08=, svid_09=, svid_10=, svid_11=, svid_12=, PDOP=2.09, HDOP=1.67, VDOP=1.25, **systemId=3**)>
<NMEA(**GN**GSA, opMode=A, navMode=3, svid_01=, svid_02=, svid_03=, svid_04=, svid_05=, svid_06=, svid_07=, svid_08=, svid_09=, svid_10=, svid_11=, svid_12=, PDOP=2.09, HDOP=1.67, VDOP=1.25, **systemId=4**)>

<NMEA(**GP**GSV, numMsg=3, msgNum=3, numSV=11, svid_01=27, elv_01=45.0, az_01=271, cno_01=14, svid_02=29, elv_02=11.0, az_02=82, cno_02=22, svid_03=31, elv_03=4.0, az_03=192, cno_03=, signalID=1)>
<NMEA(**GL**GSV, numMsg=3, msgNum=1, numSV=10, svid_01=65, elv_01=13.0, az_01=84, cno_01=17, svid_02=71, elv_02=9.0, az_02=352, cno_02=, svid_03=72, elv_03=20.0, az_03=39, cno_03=, svid_04=78, elv_04=33.0, az_04=178, cno_04=, signalID=1)>
<NMEA(**GA**GSV, numMsg=1, msgNum=1, numSV=0, signalID=7)>
<NMEA(**GB**GSV, numMsg=1, msgNum=1, numSV=0, signalID=1)>

There's no special handling of different talker IDs in the code - pynmeagps simply renders whatever comes in from the receiver. I guess I could 'synthesise' a talker ID from the systemId for GSA messages (for >=NMEA v4.10), but that seems a bit contrived.

**Comment by cminton-hub** [comment]
Your assumptions about the GSA messages are correct and you are absolutely right that the behaviour depends on the receiver.Your two examples show the differences very well. In u-center/text console, the GSA message is also only specified with the talker ID GN.  As I was reading the documentation I thought that the talker ID is handled in the same way as for the GSV message type. Of course, the same applies to the message type GRS. Since I mainly use Python and not u-center, I did not notice this immediately.

I would like to cite the GitHub repository for pymeagps using BibTeX. Would you agree to this citation?
@Misc{pymeagps, #BibText key
  author = {SEMU Consulting},
  note   = {Eingesehen am 23.01.2021},
  title  = {Python library aimed primarily at the subset of the NMEA 0183 v4 protocol for parsing of GNSS messages.},
  url    = {https://github.com/semuconsulting/pynmeagps},
}

Maybe you can add a offical citation to README.

Thank you for your reply.

**Comment by cminton-hub** [comment]
You can close this issue. Citation is especially important nowadays to separate one's own work from used sources. Most of the time it is hard to find the correct style and thus a template is quite useful.
