### ISSUE TITLE
Output number of satellite in view

### ISSUE THREAD

**Issue by Buttosaii** [semuconsulting/pynmeagps#21]
Hi, is there a command or function to output the number of satellite seen by the GNSS?

**Comment by semuadmin** [comment]
Hi @Buttosaii,

This is the sort of thing you could Google yourself (e.g. search on "_NMEA number of satellites seen_"), but in short the answer is yes, you can use the `numSV` attribute in NMEA messages like GGA, GNS or GSV, e.g.,

```
from serial import Serial
from pynmeagps import NMEAReader
stream = Serial('/dev/ttyACM0, 38400, timeout=3)
nmr = NMEAReader(stream)
(raw_data, parsed_data) = nmr.read()
if parsed_data.identity in ("GGA", "GNS", "GSV"):
   print (f"Number of satelllites tracked:  {parsed_data.numSV}")
```

Hope this helps.

FYI the [u-blox support forum](https://portal.u-blox.com/s/) is also a useful resource for technical queries though, as I say, this sort of information is in the public domain.
