### ISSUE TITLE
False / misleading label in "UBX00" (NMEA-PUBX-00) message

### ISSUE THREAD

**Issue by dbstf** [semuconsulting/pynmeagps#23]
There is a typo in the bitfield description of the "UBX00" (NMEA-PUBX-00) message in "nmeatypes_get.py".
In line 488 it says:
"**PDOP**": DE
indicating **Positional** DOP. However, according to the interface manual of the u-blox ZED-F9P receiver, and the u-center software, the field indicates **TDOP**, meaning **Time** DOP. Hence, the correct label would be
"**TDOP**": DE

**Comment by semuadmin** [comment]
Hi @dbstf Well spotted - thanks. PR will fix but needs associated change to PyGPSClient before I can issue a new release.
