### ISSUE TITLE
Cannot decode ASHR message

### ISSUE THREAD

**Issue by oe1rsa** [semuconsulting/pynmeagps#52]
**Describe the bug**

I am logging the NMEA messages to a file and the read them back by

    `with open(file, 'rb') as nmeas:
        for raw_data, parsed_data in NMEAReader (nmeas, validate = 0x03):
            print(parsed_data)`

I get the message:
    
    Unknown msgID ASHR142509.000 msgmode GET.
    
- Version: 1.0.33
- b'$PASHR,142509.000,179.885,T,-0.624,0.245,,0.029,0.029,0.502,2,3*17\r\n'

**Expected Behavior**

I expect the message to be decoded.

**Desktop (please complete the following information):**

- The operating system: Ubuntu
- The version of Python: 3.10
- The type of serial connection: N/A

**GNSS/GPS Device (please complete the following information as best you can):**

- Applanix

**Comment by semuadmin** [comment]
Hi @oe1rsa,

This appears to be a proprietary Trimble Applanix "RT300 proprietary roll and pitch" NMEA sentence, but it seems there are two alternative formats for this sentence.  The one I've already implemented (_originally taken from  https://receiverhelp.trimble.com/alloy-gnss/en-us/NMEA-0183messages_MessageOverview.html_) has an additional `msgId` attribute = "HR".

I'll review the latest available Trimble documentation and add in this definition, along with any others I'm missing.

https://receiverhelp.trimble.com/oem-gnss/NMEA-0183messages_MessageOverview.html

**Comment by oe1rsa** [comment]
Works! Thank you!
