### ISSUE TITLE
NMEAReader Checksum Validation Error

### ISSUE THREAD

**Issue by 0wulf** [semuconsulting/pynmeagps#60]
# NMEAReader Checksum Validation Error

Sorry for not foloowing the exact template. Feel free to close without resolution if you find it necessary. 
**Describe the bug**
The bug consists on the validation of the checksums when instantiating the NMEAReader class as follows: `NMEAReader(stream)`
Is probable that my GPS Server is different here but it results on the checksums failing because of the case of the letters.
![imagen](https://github.com/user-attachments/assets/a962d3cc-2b8b-44fc-9745-51cfcfccc72d)
The bug is in https://github.com/semuconsulting/pynmeagps/blob/2b9538d82ea2eb50ea18aeb3a3291677b261fec3/src/pynmeagps/nmeareader.py#L247
It's comparing strings instead of hex, so naturally "c9" != "C9"
The comparison should be done either both in lowercase or uppercase, or in a case insensitive format as decimal or hex.

**Comment by semuadmin** [comment]
Hi @0wulf,

What was your raw NMEA data source? If possible, could you send me an example of your raw data (you can redact any lat/lon if you prefer).

I’ve never come across a legitimate lower case NMEA checksum,  though a fix is easy enough.

Thanks

**Comment by 0wulf** [comment]
Hello @semuadmin 
I'm currently using my iPhone's GPS. Through an app called NMEA Gps. The app sets up a server, which I'm connecting via iPhone's hotspot from a Raspberry Pi. IDK if it is the GPS module from the phone or the server app.
Either way, here I connected to the server, and show the first and last columns (msgID and checksum i think)
![imagen](https://github.com/user-attachments/assets/377ff29e-b57e-4405-adf5-20d7a70f3561)
Thanks to you for being an active maintainer of an open source project!!

**Comment by semuadmin** [comment]
@0wulf 

It is an almost universally accepted convention that the checksum digits are transmitted as upper case. The simplest and quickest resolution may be for you to apply something like a `,$NF[:-2]+$NF[-2:].upper()` transformation to your own datastream.

But as the change is trivial, I'm happy to support this particular use case. Ideally I'd like an original, complete raw datastream to test against, but failing that can I ask you to install and test the following branch and let me know if this resolves the problem:

```shell
 pip install git+https://github.com/semuconsulting/pynmeagps.git@RC-1.0.39
```

**Comment by 0wulf** [comment]
Where can I send you the datastream?

**Comment by semuadmin** [comment]
There's an email link under "Author & License Information" at the foot of the README. Thanks.
